

INSERT INTO
    `email_templates` (
        `id`,
        `slug`,
        `name`,
        `value`,
        `created_at`,
        `updated_at`
    )
VALUES
    (
        21,
        'test-email',
        'Test Mail',
        '<p>&nbsp;</p>\r\n<!-- ----- header ---- -->\r\n<div style=\"background-color: #f8f9fa; height: 1000px;\">\r\n<div style=\"max-width: 1140px; background-color: #ebebeb; padding: 1rem 2rem 4rem; height: 45px;\">\r\n<div style=\"margin: 0 0rem 2rem 0rem;\">\r\n<h1 style=\"color: #3bb34f; float: left; padding-left: 3rem;\"><span style=\"color: #3bb34f;\"><span style=\"font-size: 32px;\"><strong>CONNECTED PERFORMANCE</strong></span></span></h1>\r\n</div>\r\n<div style=\"background-color: #fff; width: 70%; height: 470px; border-radius: 4px; margin: 5.5rem  auto 1.5rem; padding: 1.25rem; line-height: 1.6; font-size: .84rem; font-family: Arial, Helvetica, sans-serif; letter-spacing: .56px;\">\r\n<div style=\"text-align: center;\"><img style=\"object-fit: cover;\" src=\"../../custom/img/connect_logo.png\" alt=\"logo-png\" height=\"70px\" />\r\n<h1 style=\"padding-top: 0rem; font-weight: 500;\">Welcome Back!</h1>\r\n</div>\r\n<!-- ---- content ---- -->\r\n<div style=\"color: #6c757d; margin-top: 3rem; padding: 0 0.5rem;\">Dear [\"username\"]:\r\n<p style=\"margin-top: 0px;\">We are excited to see you back on this platform. Get a kick start, offer your services, and get booked by the buyers. Thanks!</p>\r\n<p style=\"padding: .4rem 0rem;\">If that doesn\'t work, copy and paste the following link in your browser:</p>\r\n<a style=\"color: #3bb34f;\" href=\"#\">[\"XXX.XXXXXXX.XXX / XXXXXXXXXXXXX\"]</a>\r\n<p style=\"padding: .4rem 0rem;\">If you have any questions, just reply to this email. We\'ll always happy to help you out.</p>\r\nCheers, <br />Connected Performance.</div>\r\n</div>\r\n<!-- ----- footer ----- -->\r\n<div style=\"background-image: linear-gradient(#cef5c9,#cef5c9); height: 40px; margin: 0 auto; width: 69%; padding: 1.5rem; font-family: Arial, Helvetica, sans-serif; border-radius: 4px; line-height: 1.6; font-size: .77rem; text-align: center;\">This email was intended for [\"user name\"], because you have signed up for Connected Performance!<br />| <a style=\"color: #3bb34f;\" href=\"#\">Unsubscribe</a><a> | The links in the email will always direct to </a><a style=\"color: #3bb34f;\" href=\"#\">www.connected-performance.com</a><a> . <br /><br /></a></div>\r\n<div style=\"margin: 0 auto; padding: 1.5rem; font-family: Arial, Helvetica, sans-serif; font-size: .7rem; width: 69%;\">\r\n<div><a style=\"color: #343a40; font-weight: bold; line-height: 1.8;\" href=\"#\">view it in your browser.</a></div>\r\n<div style=\"display: flex;\">&nbsp;</div>\r\n<div style=\"display: flex;\"><span style=\"color: #6c757d; font-size: 0.7rem;\">www.helpsoeasy.com</span></div>\r\n</div>\r\n</div>\r\n</div>',
        '2022-08-15 06:36:33',
        '2022-11-10 09:37:20'
    ),
    (
        23,
        'notificaiton',
        'Account is reactivated',
        '<p>&nbsp;</p>\r\n<!-- ----- header ---- -->\r\n<div style=\"background-color: #f8f9fa; height: 1000px;\">\r\n<div style=\"max-width: 1140px; background-color: #ebebeb; padding: 1rem 2rem 4rem; height: 45px;\">\r\n<div style=\"margin: 0 0rem 2rem 0rem;\">\r\n<h1 style=\"color: #3bb34f; float: left; padding-left: 3rem;\"><span style=\"color: #3bb34f;\"><span style=\"font-size: 32px;\"><strong>CONNECTED PERFORMANCE</strong></span></span></h1>\r\n</div>\r\n<div style=\"background-color: #fff; width: 70%; height: 470px; border-radius: 4px; margin: 5.5rem  auto 1.5rem; padding: 1.25rem; line-height: 1.6; font-size: .84rem; font-family: Arial, Helvetica, sans-serif; letter-spacing: .56px;\">\r\n<div style=\"text-align: center;\"><img style=\"object-fit: cover;\" src=\"../../custom/img/connect_logo.png\" alt=\"logo-png\" height=\"70px\" />\r\n<h1 style=\"padding-top: 0rem; font-weight: 500;\">Welcome Back!</h1>\r\n</div>\r\n<!-- ---- content ---- -->\r\n<div style=\"color: #6c757d; margin-top: 3rem; padding: 0 0.5rem;\">Dear [\"username\"]:\r\n<p style=\"margin-top: 0px;\">We are excited to see you back on this platform. Get a kick start, offer your services, and get booked by the buyers. Thanks!</p>\r\n<p style=\"padding: .4rem 0rem;\">If that doesn\'t work, copy and paste the following link in your browser:</p>\r\n<a style=\"color: #3bb34f;\" href=\"#\">[\"XXX.XXXXXXX.XXX / XXXXXXXXXXXXX\"]</a>\r\n<p style=\"padding: .4rem 0rem;\">If you have any questions, just reply to this email. We\'ll always happy to help you out.</p>\r\nCheers, <br />Connected Performance.</div>\r\n</div>\r\n<!-- ----- footer ----- -->\r\n<div style=\"background-image: linear-gradient(#cef5c9,#cef5c9); height: 40px; margin: 0 auto; width: 69%; padding: 1.5rem; font-family: Arial, Helvetica, sans-serif; border-radius: 4px; line-height: 1.6; font-size: .77rem; text-align: center;\">This email was intended for [\"user name\"], because you have signed up for Connected Performance!<br />| <a style=\"color: #3bb34f;\" href=\"#\">Unsubscribe</a><a> | The links in the email will always direct to </a><a style=\"color: #3bb34f;\" href=\"#\">www.connected-performance.com</a><a> . <br /><br /></a></div>\r\n<div style=\"margin: 0 auto; padding: 1.5rem; font-family: Arial, Helvetica, sans-serif; font-size: .7rem; width: 69%;\">\r\n<div><a style=\"color: #343a40; font-weight: bold; line-height: 1.8;\" href=\"#\">view it in your browser.</a></div>\r\n<div style=\"display: flex;\">&nbsp;</div>\r\n<div style=\"display: flex;\"><span style=\"color: #6c757d; font-size: 0.7rem;\">www.helpsoeasy.com</span></div>\r\n</div>\r\n</div>\r\n</div>',
        '2022-08-16 04:23:58',
        '2022-11-10 09:37:38'
    ),
    (
        24,
        'account-is-suspended',
        'Account is suspended',
        '<p>&nbsp;</p>\r\n<!-- ----- header ---- -->\r\n<div style=\"background-color: #f8f9fa; height: 1000px;\">\r\n<div style=\"max-width: 1140px; background-color: #ebebeb; padding: 1rem 2rem 4rem; height: 45px;\">\r\n<div style=\"margin: 0 0rem 2rem 0rem;\">\r\n<h1 style=\"color: #3bb34f; float: left; padding-left: 3rem;\"><span style=\"color: #3bb34f;\"><span style=\"font-size: 32px;\"><strong>CONNECTED PERFORMANCE</strong></span></span></h1>\r\n</div>\r\n<div style=\"background-color: #fff; width: 70%; height: 470px; border-radius: 4px; margin: 5.5rem  auto 1.5rem; padding: 1.25rem; line-height: 1.6; font-size: .84rem; font-family: Arial, Helvetica, sans-serif; letter-spacing: .56px;\">\r\n<div style=\"text-align: center;\"><img style=\"object-fit: cover;\" src=\"../../custom/img/connect_logo.png\" alt=\"logo-png\" height=\"70px\" />\r\n<h1 style=\"padding-top: 0rem; font-weight: 500;\">Welcome Back!</h1>\r\n</div>\r\n<!-- ---- content ---- -->\r\n<div style=\"color: #6c757d; margin-top: 3rem; padding: 0 0.5rem;\">Dear [\"username\"]:\r\n<p style=\"margin-top: 0px;\">We are excited to see you back on this platform. Get a kick start, offer your services, and get booked by the buyers. Thanks!</p>\r\n<p style=\"padding: .4rem 0rem;\">If that doesn\'t work, copy and paste the following link in your browser:</p>\r\n<a style=\"color: #3bb34f;\" href=\"#\">[\"XXX.XXXXXXX.XXX / XXXXXXXXXXXXX\"]</a>\r\n<p style=\"padding: .4rem 0rem;\">If you have any questions, just reply to this email. We\'ll always happy to help you out.</p>\r\nCheers, <br />Connected Performance.</div>\r\n</div>\r\n<!-- ----- footer ----- -->\r\n<div style=\"background-image: linear-gradient(#cef5c9,#cef5c9); height: 40px; margin: 0 auto; width: 69%; padding: 1.5rem; font-family: Arial, Helvetica, sans-serif; border-radius: 4px; line-height: 1.6; font-size: .77rem; text-align: center;\">This email was intended for [\"user name\"], because you have signed up for Connected Performance!<br />| <a style=\"color: #3bb34f;\" href=\"#\">Unsubscribe</a><a> | The links in the email will always direct to </a><a style=\"color: #3bb34f;\" href=\"#\">www.connected-performance.com</a><a> . <br /><br /></a></div>\r\n<div style=\"margin: 0 auto; padding: 1.5rem; font-family: Arial, Helvetica, sans-serif; font-size: .7rem; width: 69%;\">\r\n<div><a style=\"color: #343a40; font-weight: bold; line-height: 1.8;\" href=\"#\">view it in your browser.</a></div>\r\n<div style=\"display: flex;\">&nbsp;</div>\r\n<div style=\"display: flex;\"><span style=\"color: #6c757d; font-size: 0.7rem;\">www.helpsoeasy.com</span></div>\r\n</div>\r\n</div>\r\n</div>',
        '2022-08-16 04:30:52',
        '2022-11-10 09:38:07'
    ),
    (
        25,
        'account-varified',
        'Account Varified',
        '<p>&nbsp;</p>\r\n<!-- ----- header ---- -->\r\n<div style=\"background-color: #f8f9fa; height: 1000px;\">\r\n<div style=\"max-width: 1140px; background-color: #ebebeb; padding: 1rem 2rem 4rem; height: 45px;\">\r\n<div style=\"margin: 0 0rem 2rem 0rem;\">\r\n<h1 style=\"color: #3bb34f; float: left; padding-left: 3rem;\"><span style=\"color: #3bb34f;\"><span style=\"font-size: 32px;\"><strong>CONNECTED PERFORMANCE</strong></span></span></h1>\r\n</div>\r\n<div style=\"background-color: #fff; width: 70%; height: 470px; border-radius: 4px; margin: 5.5rem  auto 1.5rem; padding: 1.25rem; line-height: 1.6; font-size: .84rem; font-family: Arial, Helvetica, sans-serif; letter-spacing: .56px;\">\r\n<div style=\"text-align: center;\"><img style=\"object-fit: cover;\" src=\"../../custom/img/connect_logo.png\" alt=\"logo-png\" height=\"70px\" />\r\n<h1 style=\"padding-top: 0rem; font-weight: 500;\">Welcome Back!</h1>\r\n</div>\r\n<!-- ---- content ---- -->\r\n<div style=\"color: #6c757d; margin-top: 3rem; padding: 0 0.5rem;\">Dear [\"username\"]:\r\n<p style=\"margin-top: 0px;\">We are excited to see you back on this platform. Get a kick start, offer your services, and get booked by the buyers. Thanks!</p>\r\n<p style=\"padding: .4rem 0rem;\">If that doesn\'t work, copy and paste the following link in your browser:</p>\r\n<a style=\"color: #3bb34f;\" href=\"#\">[\"XXX.XXXXXXX.XXX / XXXXXXXXXXXXX\"]</a>\r\n<p style=\"padding: .4rem 0rem;\">If you have any questions, just reply to this email. We\'ll always happy to help you out.</p>\r\nCheers, <br />Connected Performance.</div>\r\n</div>\r\n<!-- ----- footer ----- -->\r\n<div style=\"background-image: linear-gradient(#cef5c9,#cef5c9); height: 40px; margin: 0 auto; width: 69%; padding: 1.5rem; font-family: Arial, Helvetica, sans-serif; border-radius: 4px; line-height: 1.6; font-size: .77rem; text-align: center;\">This email was intended for [\"user name\"], because you have signed up for Connected Performance!<br />| <a style=\"color: #3bb34f;\" href=\"#\">Unsubscribe</a><a> | The links in the email will always direct to </a><a style=\"color: #3bb34f;\" href=\"#\">www.connected-performance.com</a><a> . <br /><br /></a></div>\r\n<div style=\"margin: 0 auto; padding: 1.5rem; font-family: Arial, Helvetica, sans-serif; font-size: .7rem; width: 69%;\">\r\n<div><a style=\"color: #343a40; font-weight: bold; line-height: 1.8;\" href=\"#\">view it in your browser.</a></div>\r\n<div style=\"display: flex;\">&nbsp;</div>\r\n<div style=\"display: flex;\"><span style=\"color: #6c757d; font-size: 0.7rem;\">www.helpsoeasy.com</span></div>\r\n</div>\r\n</div>\r\n</div>',
        '2022-08-16 04:41:45',
        '2022-11-10 09:38:22'
    ),
    (
        26,
        'account-activated',
        'Account Activated',
        '<p>&nbsp;</p>\r\n<!-- ----- header ---- -->\r\n<div style=\"background-color: #f8f9fa; height: 1000px;\">\r\n<div style=\"max-width: 1140px; background-color: #ebebeb; padding: 1rem 2rem 4rem; height: 45px;\">\r\n<div style=\"margin: 0 0rem 2rem 0rem;\">\r\n<h1 style=\"color: #3bb34f; float: left; padding-left: 3rem;\"><span style=\"color: #3bb34f;\"><span style=\"font-size: 32px;\"><strong>CONNECTED PERFORMANCE</strong></span></span></h1>\r\n</div>\r\n<div style=\"background-color: #fff; width: 70%; height: 470px; border-radius: 4px; margin: 5.5rem  auto 1.5rem; padding: 1.25rem; line-height: 1.6; font-size: .84rem; font-family: Arial, Helvetica, sans-serif; letter-spacing: .56px;\">\r\n<div style=\"text-align: center;\"><img style=\"object-fit: cover;\" src=\"../../custom/img/connect_logo.png\" alt=\"logo-png\" height=\"70px\" />\r\n<h1 style=\"padding-top: 0rem; font-weight: 500;\">Welcome Back!</h1>\r\n</div>\r\n<!-- ---- content ---- -->\r\n<div style=\"color: #6c757d; margin-top: 3rem; padding: 0 0.5rem;\">Dear [\"username\"]:\r\n<p style=\"margin-top: 0px;\">We are excited to see you back on this platform. Get a kick start, offer your services, and get booked by the buyers. Thanks!</p>\r\n<p style=\"padding: .4rem 0rem;\">If that doesn\'t work, copy and paste the following link in your browser:</p>\r\n<a style=\"color: #3bb34f;\" href=\"#\">[\"XXX.XXXXXXX.XXX / XXXXXXXXXXXXX\"]</a>\r\n<p style=\"padding: .4rem 0rem;\">If you have any questions, just reply to this email. We\'ll always happy to help you out.</p>\r\nCheers, <br />Connected Performance.</div>\r\n</div>\r\n<!-- ----- footer ----- -->\r\n<div style=\"background-image: linear-gradient(#cef5c9,#cef5c9); height: 40px; margin: 0 auto; width: 69%; padding: 1.5rem; font-family: Arial, Helvetica, sans-serif; border-radius: 4px; line-height: 1.6; font-size: .77rem; text-align: center;\">This email was intended for [\"user name\"], because you have signed up for Connected Performance!<br />| <a style=\"color: #3bb34f;\" href=\"#\">Unsubscribe</a><a> | The links in the email will always direct to </a><a style=\"color: #3bb34f;\" href=\"#\">www.connected-performance.com</a><a> . <br /><br /></a></div>\r\n<div style=\"margin: 0 auto; padding: 1.5rem; font-family: Arial, Helvetica, sans-serif; font-size: .7rem; width: 69%;\">\r\n<div><a style=\"color: #343a40; font-weight: bold; line-height: 1.8;\" href=\"#\">view it in your browser.</a></div>\r\n<div style=\"display: flex;\">&nbsp;</div>\r\n<div style=\"display: flex;\"><span style=\"color: #6c757d; font-size: 0.7rem;\">www.helpsoeasy.com</span></div>\r\n</div>\r\n</div>\r\n</div>',
        '2022-08-16 05:07:38',
        '2022-11-10 09:38:39'
    ),
    (
        27,
        'account-deleted',
        'Account Deleted',
        '<p>&nbsp;</p>\r\n<!-- ----- header ---- -->\r\n<div style=\"background-color: #f8f9fa; height: 1000px;\">\r\n<div style=\"max-width: 1140px; background-color: #ebebeb; padding: 1rem 2rem 4rem; height: 45px;\">\r\n<div style=\"margin: 0 0rem 2rem 0rem;\">\r\n<h1 style=\"color: #3bb34f; float: left; padding-left: 3rem;\"><span style=\"color: #3bb34f;\"><span style=\"font-size: 32px;\"><strong>CONNECTED PERFORMANCE</strong></span></span></h1>\r\n</div>\r\n<div style=\"background-color: #fff; width: 70%; height: 470px; border-radius: 4px; margin: 5.5rem  auto 1.5rem; padding: 1.25rem; line-height: 1.6; font-size: .84rem; font-family: Arial, Helvetica, sans-serif; letter-spacing: .56px;\">\r\n<div style=\"text-align: center;\"><img style=\"object-fit: cover;\" src=\"../../custom/img/connect_logo.png\" alt=\"logo-png\" height=\"70px\" />\r\n<h1 style=\"padding-top: 0rem; font-weight: 500;\">Welcome Back!</h1>\r\n</div>\r\n<!-- ---- content ---- -->\r\n<div style=\"color: #6c757d; margin-top: 3rem; padding: 0 0.5rem;\">Dear [\"username\"]:\r\n<p style=\"margin-top: 0px;\">We are excited to see you back on this platform. Get a kick start, offer your services, and get booked by the buyers. Thanks!</p>\r\n<p style=\"padding: .4rem 0rem;\">If that doesn\'t work, copy and paste the following link in your browser:</p>\r\n<a style=\"color: #3bb34f;\" href=\"#\">[\"XXX.XXXXXXX.XXX / XXXXXXXXXXXXX\"]</a>\r\n<p style=\"padding: .4rem 0rem;\">If you have any questions, just reply to this email. We\'ll always happy to help you out.</p>\r\nCheers, <br />Connected Performance.</div>\r\n</div>\r\n<!-- ----- footer ----- -->\r\n<div style=\"background-image: linear-gradient(#cef5c9,#cef5c9); height: 40px; margin: 0 auto; width: 69%; padding: 1.5rem; font-family: Arial, Helvetica, sans-serif; border-radius: 4px; line-height: 1.6; font-size: .77rem; text-align: center;\">This email was intended for [\"user name\"], because you have signed up for Connected Performance!<br />| <a style=\"color: #3bb34f;\" href=\"#\">Unsubscribe</a><a> | The links in the email will always direct to </a><a style=\"color: #3bb34f;\" href=\"#\">www.connected-performance.com</a><a> . <br /><br /></a></div>\r\n<div style=\"margin: 0 auto; padding: 1.5rem; font-family: Arial, Helvetica, sans-serif; font-size: .7rem; width: 69%;\">\r\n<div><a style=\"color: #343a40; font-weight: bold; line-height: 1.8;\" href=\"#\">view it in your browser.</a></div>\r\n<div style=\"display: flex;\">&nbsp;</div>\r\n<div style=\"display: flex;\"><span style=\"color: #6c757d; font-size: 0.7rem;\">www.helpsoeasy.com</span></div>\r\n</div>\r\n</div>\r\n</div>',
        '2022-08-16 05:28:44',
        '2022-11-10 09:38:51'
    ),
    (
        37,
        'Login',
        'Login',
        '<p>&nbsp;</p>\r\n<!-- ----- header ---- -->\r\n<div style=\"background-color: #f8f9fa; height: 1000px;\">\r\n<div style=\"max-width: 1140px; background-color: #ebebeb; padding: 1rem 2rem 4rem; height: 45px;\">\r\n<div style=\"margin: 0 0rem 2rem 0rem;\">\r\n<h1 style=\"color: #3bb34f; float: left; padding-left: 3rem;\"><span style=\"color: #3bb34f;\"><span style=\"font-size: 32px;\"><strong>CONNECTED PERFORMANCE</strong></span></span></h1>\r\n</div>\r\n<div style=\"background-color: #fff; width: 70%; height: 470px; border-radius: 4px; margin: 5.5rem  auto 1.5rem; padding: 1.25rem; line-height: 1.6; font-size: .84rem; font-family: Arial, Helvetica, sans-serif; letter-spacing: .56px;\">\r\n<div style=\"text-align: center;\"><img style=\"object-fit: cover;\" src=\"../../custom/img/connect_logo.png\" alt=\"logo-png\" height=\"70px\" />\r\n<h1 style=\"padding-top: 0rem; font-weight: 500;\">Welcome Back!</h1>\r\n</div>\r\n<!-- ---- content ---- -->\r\n<div style=\"color: #6c757d; margin-top: 3rem; padding: 0 0.5rem;\">Dear [\"username\"]:\r\n<p style=\"margin-top: 0px;\">We are excited to see you back on this platform. Get a kick start, offer your services, and get booked by the buyers. Thanks!</p>\r\n<p style=\"padding: .4rem 0rem;\">If that doesn\'t work, copy and paste the following link in your browser:</p>\r\n<a style=\"color: #3bb34f;\" href=\"#\">[\"XXX.XXXXXXX.XXX / XXXXXXXXXXXXX\"]</a>\r\n<p style=\"padding: .4rem 0rem;\">If you have any questions, just reply to this email. We\'ll always happy to help you out.</p>\r\nCheers, <br />Connected Performance.</div>\r\n</div>\r\n<!-- ----- footer ----- -->\r\n<div style=\"background-image: linear-gradient(#cef5c9,#cef5c9); height: 40px; margin: 0 auto; width: 69%; padding: 1.5rem; font-family: Arial, Helvetica, sans-serif; border-radius: 4px; line-height: 1.6; font-size: .77rem; text-align: center;\">This email was intended for [\"user name\"], because you have signed up for Connected Performance!<br />| <a style=\"color: #3bb34f;\" href=\"#\">Unsubscribe</a><a> | The links in the email will always direct to </a><a style=\"color: #3bb34f;\" href=\"#\">www.connected-performance.com</a><a> . <br /><br /></a></div>\r\n<div style=\"margin: 0 auto; padding: 1.5rem; font-family: Arial, Helvetica, sans-serif; font-size: .7rem; width: 69%;\">\r\n<div><a style=\"color: #343a40; font-weight: bold; line-height: 1.8;\" href=\"#\">view it in your browser.</a></div>\r\n<div style=\"display: flex;\">&nbsp;</div>\r\n<div style=\"display: flex;\"><span style=\"color: #6c757d; font-size: 0.7rem;\">www.helpsoeasy.com</span></div>\r\n</div>\r\n</div>\r\n</div>',
        '2022-08-16 08:35:25',
        '2022-11-10 09:39:04'
    ),
    (
        52,
        'Welcome',
        'Welcome',
        '<p>&nbsp;</p>\r\n<!-- ----- header ---- -->\r\n<div style=\"background-color: #f8f9fa; height: 1000px;\">\r\n<div style=\"max-width: 1140px; background-color: #ebebeb; padding: 1rem 2rem 4rem; height: 45px;\">\r\n<div style=\"margin: 0 0rem 2rem 0rem;\">\r\n<h1 style=\"color: #3bb34f; float: left; padding-left: 3rem;\"><span style=\"color: #3bb34f;\"><span style=\"font-size: 32px;\"><strong>CONNECTED PERFORMANCE</strong></span></span></h1>\r\n</div>\r\n<div style=\"background-color: #fff; width: 70%; height: 470px; border-radius: 4px; margin: 5.5rem  auto 1.5rem; padding: 1.25rem; line-height: 1.6; font-size: .84rem; font-family: Arial, Helvetica, sans-serif; letter-spacing: .56px;\">\r\n<div style=\"text-align: center;\"><img style=\"object-fit: cover;\" src=\"../../custom/img/connect_logo.png\" alt=\"logo-png\" height=\"70px\" />\r\n<h1 style=\"padding-top: 0rem; font-weight: 500;\">Welcome Back!</h1>\r\n</div>\r\n<!-- ---- content ---- -->\r\n<div style=\"color: #6c757d; margin-top: 3rem; padding: 0 0.5rem;\">Dear [\"username\"]:\r\n<p style=\"margin-top: 0px;\">We are excited to see you back on this platform. Get a kick start, offer your services, and get booked by the buyers. Thanks!</p>\r\n<p style=\"padding: .4rem 0rem;\">If that doesn\'t work, copy and paste the following link in your browser:</p>\r\n<a style=\"color: #3bb34f;\" href=\"#\">[\"XXX.XXXXXXX.XXX / XXXXXXXXXXXXX\"]</a>\r\n<p style=\"padding: .4rem 0rem;\">If you have any questions, just reply to this email. We\'ll always happy to help you out.</p>\r\nCheers, <br />Connected Performance.</div>\r\n</div>\r\n<!-- ----- footer ----- -->\r\n<div style=\"background-image: linear-gradient(#cef5c9,#cef5c9); height: 40px; margin: 0 auto; width: 69%; padding: 1.5rem; font-family: Arial, Helvetica, sans-serif; border-radius: 4px; line-height: 1.6; font-size: .77rem; text-align: center;\">This email was intended for [\"user name\"], because you have signed up for Connected Performance!<br />| <a style=\"color: #3bb34f;\" href=\"#\">Unsubscribe</a><a> | The links in the email will always direct to </a><a style=\"color: #3bb34f;\" href=\"#\">www.connected-performance.com</a><a> . <br /><br /></a></div>\r\n<div style=\"margin: 0 auto; padding: 1.5rem; font-family: Arial, Helvetica, sans-serif; font-size: .7rem; width: 69%;\">\r\n<div><a style=\"color: #343a40; font-weight: bold; line-height: 1.8;\" href=\"#\">view it in your browser.</a></div>\r\n<div style=\"display: flex;\">&nbsp;</div>\r\n<div style=\"display: flex;\"><span style=\"color: #6c757d; font-size: 0.7rem;\">www.helpsoeasy.com</span></div>\r\n</div>\r\n</div>\r\n</div>',
        '2022-08-17 04:36:39',
        '2022-11-10 09:39:18'
    ),
    (
        53,
        'welcome-back',
        'Welcome Back',
        '<p>&nbsp;</p>\r\n<!-- ----- header ---- -->\r\n<div style=\"background-color: #f8f9fa; height: 1000px;\">\r\n<div style=\"max-width: 1140px; background-color: #ebebeb; padding: 1rem 2rem 4rem; height: 45px;\">\r\n<div style=\"margin: 0 0rem 2rem 0rem;\">\r\n<h1 style=\"color: #3bb34f; float: left; padding-left: 3rem;\"><span style=\"color: #3bb34f;\"><span style=\"font-size: 32px;\"><strong>CONNECTED PERFORMANCE</strong></span></span></h1>\r\n</div>\r\n<div style=\"background-color: #fff; width: 70%; height: 470px; border-radius: 4px; margin: 5.5rem  auto 1.5rem; padding: 1.25rem; line-height: 1.6; font-size: .84rem; font-family: Arial, Helvetica, sans-serif; letter-spacing: .56px;\">\r\n<div style=\"text-align: center;\"><img style=\"object-fit: cover;\" src=\"../../custom/img/connect_logo.png\" alt=\"logo-png\" height=\"70px\" />\r\n<h1 style=\"padding-top: 0rem; font-weight: 500;\">Welcome Back!</h1>\r\n</div>\r\n<!-- ---- content ---- -->\r\n<div style=\"color: #6c757d; margin-top: 3rem; padding: 0 0.5rem;\">Dear [\"username\"]:\r\n<p style=\"margin-top: 0px;\">We are excited to see you back on this platform. Get a kick start, offer your services, and get booked by the buyers. Thanks!</p>\r\n<p style=\"padding: .4rem 0rem;\">If that doesn\'t work, copy and paste the following link in your browser:</p>\r\n<a style=\"color: #3bb34f;\" href=\"#\">[\"XXX.XXXXXXX.XXX / XXXXXXXXXXXXX\"]</a>\r\n<p style=\"padding: .4rem 0rem;\">If you have any questions, just reply to this email. We\'ll always happy to help you out.</p>\r\nCheers, <br />Connected Performance.</div>\r\n</div>\r\n<!-- ----- footer ----- -->\r\n<div style=\"background-image: linear-gradient(#cef5c9,#cef5c9); height: 40px; margin: 0 auto; width: 69%; padding: 1.5rem; font-family: Arial, Helvetica, sans-serif; border-radius: 4px; line-height: 1.6; font-size: .77rem; text-align: center;\">This email was intended for [\"user name\"], because you have signed up for Connected Performance!<br />| <a style=\"color: #3bb34f;\" href=\"#\">Unsubscribe</a><a> | The links in the email will always direct to </a><a style=\"color: #3bb34f;\" href=\"#\">www.connected-performance.com</a><a> . <br /><br /></a></div>\r\n<div style=\"margin: 0 auto; padding: 1.5rem; font-family: Arial, Helvetica, sans-serif; font-size: .7rem; width: 69%;\">\r\n<div><a style=\"color: #343a40; font-weight: bold; line-height: 1.8;\" href=\"#\">view it in your browser.</a></div>\r\n<div style=\"display: flex;\">&nbsp;</div>\r\n<div style=\"display: flex;\"><span style=\"color: #6c757d; font-size: 0.7rem;\">www.helpsoeasy.com</span></div>\r\n</div>\r\n</div>\r\n</div>',
        '2022-08-17 04:42:17',
        '2022-11-10 09:36:47'
    );

